name: CI/CD

on:
    push:
        branches:
            - main
            - feat/pipable-stream
            - feat/rspack
    pull_request:
        branches:
            - main
            - feat/rspack

jobs:
    pnpm:
        uses: ./.github/workflows/pnpm-cache.yml

    test:
        needs: pnpm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup
            - run: pnpm test

    lint:
        needs: pnpm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup
            - run: pnpm lint

    build:
        needs: pnpm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup
            - run: pnpm prod:build
